POST http://localhost:8000/auth/register
Accept: application/json
Content-Type: application/json

{
  "name": "ALberto Gon",
  "email": "albert@example.com",
  "password": "189875623"
}

### ver todos los usuarios


GET http://localhost:8000/user/index
Accept: application/json
Content-Type: application/json


### logearse con google

POST http://localhost:8000/auth/oauth
Accept: application/json
Content-Type: application/json

### subir archivos

POST http://localhost:8000/files/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="examen.png"
Content-Type: image/png

< ./uploads/examen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### subir archivos local

POST http://localhost:8000/files/uploadLocal
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="captura.jpg"
Content-Type: image/jpeg

< ./uploads/captura.png
--WebAppBoundary--
### prueba


